### ISSUE TITLE
Python 2/3 'str' does not support the buffer interface.

### ISSUE THREAD

**Issue by brantleyr** [RedHatInsights/insights-core#1014]
When running "2and3" branch for Python 3 support.

`2018-03-13 11:18:15,537    DEBUG insights.client.collection_rules Attemping to download collection rules from https://cert-api.access.redhat.com/r/insights/v1/static/uploader.json
2018-03-13 11:18:15,564    DEBUG insights.client.collection_rules Successfully downloaded collection rules
2018-03-13 11:18:15,604    ERROR insights.client.phase.v1 Fatal error
Traceback (most recent call last):
  File "/etc/insights-client/rpm.egg/insights/client/phase/v1.py", line 30, in _f
    func()
  File "/etc/insights-client/rpm.egg/insights/client/phase/v1.py", line 114, in update
    c.update_rules()
  File "/etc/insights-client/rpm.egg/insights/client/__init__.py", line 294, in update_rules
    return client.update_rules()
  File "/etc/insights-client/rpm.egg/insights/client/client.py", line 235, in update_rules
    return pc.get_conf(True, {})
  File "/etc/insights-client/rpm.egg/insights/client/collection_rules.py", line 200, in get_conf
    dyn_conf = self.get_collection_rules()
  File "/etc/insights-client/rpm.egg/insights/client/collection_rules.py", line 112, in get_collection_rules
    json_response.write(req.text)
  File "/usr/lib64/python3.4/tempfile.py", line 417, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface
2018-03-13 11:18:15,652    DEBUG insights_client Attempt failed.
[root@rhel7serv2 insights-client]#
`

**Comment by jhjaggars** [comment]
@brantleyr Did you address this by opening the `NamedTemporaryFile` in text mode?
