### ISSUE TITLE
utf-8 UnicodeDecodeError in 'var/log/messages' parsing

### ISSUE THREAD

**Issue by JoySnow** [RedHatInsights/insights-core#1432]
A example of this broken:
```
(insights-cli-venv) ╭[localhost] ~/Work/insights-cli-venv
╰> insights-cli  --component-modules diag_insights_rules.plugins.storage.lun_assignment_changed --verbose  -- ~/Downloads/sosreport-example.tar.xz
...
INFO     Trying insights.parsers.messages.Messages
DEBUG    [['grep', '-F', 'kernel', '/tmp/insights-PRsYcB/sosreport-example/var/log/messages']]
WARNING  Traceback (most recent call last):
  File "/home/joy/Work/insights-core/insights/core/dr.py", line 689, in run
    result = DELEGATES[component].process(broker)
  File "/home/joy/Work/insights-core/insights/core/dr.py", line 501, in process
    return self.invoke(broker)
  File "/home/joy/Work/insights-core/insights/core/plugins.py", line 51, in invoke
    return self.component(dep_value)
  File "/home/joy/Work/insights-core/insights/core/__init__.py", line 82, in __init__
    self._handle_content(context)
  File "/home/joy/Work/insights-core/insights/core/__init__.py", line 85, in _handle_content
    self.parse_content(context.content)
  File "/home/joy/Work/insights-core/insights/core/spec_factory.py", line 104, in content
    self._content = self.load()
  File "/home/joy/Work/insights-core/insights/core/spec_factory.py", line 178, in load
    rc, out = self.ctx.shell_out(cmd, keep_rc=True, env=SAFE_ENV)
  File "/home/joy/Work/insights-core/insights/core/context.py", line 142, in shell_out
    raw = self.check_output(cmd, timeout=timeout, keep_rc=keep_rc, env=env)
  File "/home/joy/Work/insights-core/insights/core/context.py", line 138, in check_output
    keep_rc=keep_rc, env=env)
  File "/home/joy/Work/insights-core/insights/util/subproc.py", line 117, in call
    return rc, output.decode(output_encoding) if output_encoding else output
  File "/home/joy/Work/insights-cli-venv/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd2 in position 1407487: invalid continuation byte
```
Solution: 
Replace `output.decode(output_encoding)` with `output.decode(output_encoding, errors='ignore')` .

**Comment by xiangce** [comment]
Hi @JoySnow , would you please to provide a system_id whose archive would cause this problem?

**Comment by xiangce** [comment]
Below lines which contain undisplayable characters will cause this problem:
~~~
  1 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: FFFF 00000000bddac280 00064 (v02 HP     ProLiant 00000002   Ò? 0000162E)
  2 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: SPMI 00000000bddac300 00040 (v05 HP     ProLiant 00000001   Ò? 0000162E)
  3 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: ERST 00000000bddac340 00230 (v01 HP     ProLiant 00000001   Ò? 0000162E)
  4 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: APIC 00000000bddac580 0026A (v01 HP     ProLiant 00000002      00000000)
  5 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: SRAT 00000000bddac800 00750 (v01 HP     Proliant 00000001   Ò? 0000162E)
  6 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: FFFF 00000000bddacf80 00176 (v01 HP     ProLiant 00000001   Ò? 0000162E)
  7 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: BERT 00000000bddad100 00030 (v01 HP     ProLiant 00000001   Ò? 0000162E)
  8 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: HEST 00000000bddad140 000BC (v01 HP     ProLiant 00000001   Ò? 0000162E)
  9 Jun  2 16:16:24 AHDPDCEVATAPP3 kernel: ACPI: DMAR 00000000bddad200 00684 (v01 HP     ProLiant 00000001   Ò? 0000162E)
~~~
