### ISSUE TITLE
RedhatRelease parser failed to parse minor release version in some scenarios

### ISSUE THREAD

**Issue by pratikgadiya12** [RedHatInsights/insights-core#1590]
In few cases where redhat_release content is something similar to below, RedhatRelease parser fails to get the minor version extracted from it

Run:
```
>>> from insights.parsers.redhat_release import RedhatRelease
>>> from insights.tests import context_wrap
>>> RedhatRelease(context_wrap("Red Hat Enterprise Linux release 7.5-0.14")).major
7
>>> RedhatRelease(context_wrap("Red Hat Enterprise Linux release 7.5-0.14")).minor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/insights/insights-core/insights/parsers/redhat_release.py", line 59, in minor
    return int(s[1])
ValueError: invalid literal for int() with base 10: '5-0'
>>> RedhatRelease(context_wrap("Red Hat Enterprise Linux release 7.5-0.14")).version
'7.5-0.14'
```

**Comment by bfahr** [comment]
Fixed by #1641
