### ISSUE TITLE
get_max(package_name) returns TypeError for some package lists

### ISSUE THREAD

**Issue by jdobes** [RedHatInsights/insights-core#1839]
When parsing installed package lists from various Insights archives, using get_max function to get newest package version of given package name throws often this error:

```
2019-04-15 20:08:51,852:ERROR:__main__:Unable to parse archive: 'Traceback (most recent call last):
File "/listener/listener/upload_listener.py", line 100, in process_upload\n    parser.parse()\n
File "/listener/listener/archive_parser.py", line 62, in parse\n    pkg = pkglist.get_max(pkg_name)\n
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 211, in get_max\n   return max(self.packages[package_name])\n
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 599, in __gt__\n    return isinstance(other, InstalledRpm) and other.__lt__(self)\n
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 584, in __lt__\n    return self_v < other_v\nTypeError: \'<\' not supported between instances of \'int\' and \'str\''|
```

**Comment by chenlizhong** [comment]
@jdobes 

Do you have an example installed package lists that triggered this error?

**Comment by jdobes** [comment]
This package entry is causing issues
```
{"name":"gpg-pubkey","epoch":"(none)","version":"2fa658e0","release":"45700c69","arch":"(none)","installtime":"Thu Apr 25 08:21:00 2019","buildtime":"1556194860","vendor":"(none)","buildhost":"localhost","sigpgp":"(none)"}
```

when get_max is called

```
broker[Installed].get_max("gpg-pubkey")
```

**Comment by chenlizhong** [comment]
`gpg-pubkey` is special one. It is rpm name style, but it is not version and release. 
Do not compare for it.

**Comment by tlestach** [comment]
gpg-pubkey is a valid rpm, collected by the insights-client. If insights-core is the preferred library to work with the archives, I'd expect it to support this case as well. Besides that it's not clear, whether gpg-pubkey is the only rpm, that causes the traceback, or whether it's just a example of many.

# rpm -qi gpg-pubkey-2fa658e0-45700c69 | head -n 15
Name        : gpg-pubkey
Version     : 2fa658e0
Release     : 45700c69
Architecture: (none)
Install Date: Fri 07 Oct 2016 07:29:38 AM EDT
Group       : Public Keys
Size        : 0
License     : pubkey
Signature   : (none)
Source RPM  : (none)
Build Date  : Fri 01 Dec 2006 06:05:13 AM EST
Build Host  : localhost
Relocations : (not relocatable)
Packager    : Red Hat, Inc. (auxiliary key) <security@redhat.com>
Summary     : gpg(Red Hat, Inc. (auxiliary key) <security@redhat.com>)

**Comment by jdobes** [comment]
I think this is a problem of insights-core. Yes, `gpg-pubkey` is special package and yes, getting newest version of this package doesn't make sense. But since insights-core parses this package into `InstalledRpm` object, it should also make sure that it's `__lt__` method doesn't crash. Or make sure that such packages are ignored by parser.

**Comment by ggainey** [comment]
Another package that fails in get_max:

2019-05-06 15:03:37,946:ERROR:__main__:Unable to parse archive: 'Traceback (most recent call last):\n  File "/listener/listener/upload_listener.py", line 141, in parse_archive\n    parser.parse()\n  File "/listener/listener/archive_parser.py", line 65, in parse\n    pkg = pkglist.get_max(pkg_name)\n  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 211, in get_max\n    return max(self.packages[package_name])\n  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 599, in __gt__\n    return isinstance(other, InstalledRpm) and other.__lt__(self)\n  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 575, in __lt__\n    if self == other:\n  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 555, in __eq__\n    .format(self.package, other.package))\nValueError: Cannot compare packages that one has distribution while the other does not nagios-plugins-disk-2.2.1-16.20180725git3429dad.el7 != nagios-plugins-disk-2.2.1-9git5c7eb5b9.el7'|

Red Hat NEVRAs can be kind of filthy - code that claims to be able to do NEVRA-comparisons, has to Not Barf in the presence of suboptimal NEVRAs. get_max() has *got* to be more robust, you can't push the problem off on the users of the library.

**Comment by ggainey** [comment]
And another:


2019-05-06 14:48:42,470:ERROR:__main__:Unable to parse archive: 'Traceback (most recent call last):\n  File "/listener/listener/upload_listener.py", line 141, in parse_archive\n    parser.parse()\n  File "/listener/listener/archive_parser.py", line 65, in parse\n    pkg = pkglist.get_max(pkg_name)\n  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 211, in get_max\n    return max(self.packages[package_name])\n  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 599, in __gt__\n    return isinstance(other, InstalledRpm) and other.__lt__(self)\n  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 575, in __lt__\n    if self == other:\n  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/insights/parsers/installed_rpms.py", line 555, in __eq__\n    .format(self.package, other.package))\nValueError: Cannot compare packages that one has distribution while the other does not xz-5.2.2-1.el7 != xz-5.1.2-12alpha.el7'\|
--

**Comment by tlestach** [comment]
@jhjaggars can you please help? get_max tracebacks cause us errors and processing failures what results in not processing incoming archives.
(We temporarily blacklisted gpg-pubkey package, but it looks like there're much more packages that insights-core has troubles to process.)

**Comment by ggainey** [comment]
Failures vulnerability-engine-listener, upload_archive.py, attached

[get_max_failures-2019-05-04-20:08:53_to_2019-05-06-15:51:30.gz](https://github.com/RedHatInsights/insights-core/files/3148848/get_max_failures-2019-05-04-20.08.53_to_2019-05-06-15.51.30.gz)

**Comment by csams** [comment]
@ggainey thanks! I strongly suspect these are coming from a machine or machines who are using an old version of the client pinned to the old uploader.json that tells it what to collect. We changed the rpm invocation a long time ago to disambiguate the different rpm fields in the output, but the old spec that's out there supporting one of the first clients still has the old command.

**Comment by chenlizhong** [comment]
Current code can not handle below two compare.  it will raise Value error "Cannot compare packages that one has distribution while the other does not"

nagios-plugins-disk-2.2.1-16.20180725git3429dad.el7
 nagios-plugins-disk-2.2.1-9git5c7eb5b9.el7

xz-5.2.2-1.el7 
 xz-5.1.2-12alpha.el7

Root cause is the distribution is None for  xz-5.1.2-12alpha.el7 and nagios-plugins-disk-2.2.1-9git5c7eb5b9.el7

Code fragment:

~~~
        def _start_of_distribution(rest_split):
            """
            The start of distribution field: from the right, the last non-digit part
            - bash-4.2.39-3.el7_2.2
              distribution: el7_2.2
            - kernel-rt-debug-3.10.0-327.rt56.204.el7
              distribution: el7
            """
            nondigit_flag = False
            for i, r in enumerate(reversed(rest_split)):
                if not r.isdigit():
                    nondigit_flag = True
                elif nondigit_flag and r.isdigit():
                    return len(rest_split) - i

        self._release_sep = self.release
        self._distribution = None
        rl_split = self._release_sep.split('.') if self._release_sep else None
~~~

~~~
        if (not self._distribution) != (not other._distribution):
            raise ValueError('Cannot compare packages that one has distribution while the other does not {0} != {1}'
                             .format(self.package, other.package))
~~~

**Comment by chenlizhong** [comment]
Fix ValueError: Cannot compare packages that one has distribution while the other does not xz-5.2.2-1.el7 != xz-5.1.2-12alpha.el7 by below PR

https://github.com/RedHatInsights/insights-core/pull/1913

**Comment by MichaelMraka** [comment]
A complete fix for rpm comparison: #1914

**Comment by csams** [comment]
I'm working on a PR for #1839 that doesn't require external dependencies and passes all of the tests in the [rpm tests](https://raw.githubusercontent.com/rpm-software-management/rpm/master/tests/rpmvercmp.at).

**Comment by MichaelMraka** [comment]
Actually the most easiest way is to use rpm's python interface itself...

```
import rpm 

rpm.labelCompare((self.epoch, self.version, self.release),
                                   (other.epoch, other.version, other.release))
```

The only thing you need is to put ``rpm-python`` (or ``rpm-python3``) package into your rpm dependencies.
