### ISSUE TITLE
Enhance parser RabbitMQReport 

### ISSUE THREAD

**Issue by JoySnow** [RedHatInsights/insights-core#1906]
For some input data, this current `RabbitMQReport` parser fails and hides errors.
Enhancement is required.

**Comment by JoySnow** [comment]
Related to https://github.com/RedHatInsights/insights-core/issues/1

**Comment by chenlizhong** [comment]
Call trace:

~~~
WARNING:insights.core.dr:Traceback (most recent call last):
  File "/home/brq/user_a/insights-core/insights/core/dr.py", line 952, in run
    result = DELEGATES[component].process(broker)
  File "/home/brq/user_a/insights-core/insights/core/plugins.py", line 272, in process
    r = self.invoke(broker)
  File "/home/brq/user_a/insights-core/insights/core/plugins.py", line 63, in invoke
    return super(PluginType, self).invoke(broker)
  File "/home/brq/user_a/insights-core/insights/core/dr.py", line 653, in invoke
    return self.component(*args)
  File "rabbitmq_report.py", line 13, in report
    result = create_parser().parseString("\n".join(rabbitmq_report.content)).asDict()
  File "/home/brq/user_a/insights-core/insights/contrib/pyparsing.py", line 1217, in parseString
    raise exc
ParseException: Expected "}" (at char 825), (line:17, col:123)
~~~
