### ISSUE TITLE
`SysconfigOptions` base parser does not parse unpaired quoted lines

### ISSUE THREAD

**Issue by akshay196** [RedHatInsights/insights-core#1946]
When there is sysconfig file contains unpaired quotations, `SysconfigOptions` base parser throws `ValueError` at [line-489 in parse_content](https://github.com/RedHatInsights/insights-core/blob/master/insights/core/__init__.py#L489).

Exception caught for `KEY='VALUE_UNPAIRED_QUOTED"` is as below:
```
Traceback (most recent call last):
  File "/home/user/insights/insights-core/insights/core/__init__.py", line 486, in parse_content
    words = shlex.split(line)
  File "/usr/lib64/python3.7/shlex.py", line 305, in split
    return list(lex)
  File "/usr/lib64/python3.7/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.7/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.7/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/insights/insights-core/insights/core/dr.py", line 954, in run
    result = DELEGATES[component].process(broker)
  File "/home/user/insights/insights-core/insights/core/dr.py", line 673, in process
    return self.invoke(broker)
  File "/home/user/insights/insights-core/insights/core/plugins.py", line 123, in invoke
    return self.component(dep_value)
  File "/home/user/insights/insights-core/insights/core/__init__.py", line 82, in __init__
    self._handle_content(context)
  File "/home/user/insights/insights-core/insights/core/__init__.py", line 85, in _handle_content
    self.parse_content(context.content)
  File "/home/user/insights/insights-core/insights/core/__init__.py", line 489, in parse_content
    line, comment = line.split(' #', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Expected output:**
The parser should parse unpaired quoted lines without error. It should return data like this:
```
{'KEY': '\'VALUE_WITHOUT_CLOSING_QUOTATION"'}
```

**Comment by bfahr** [comment]
@akshay196 is this a common problem to have the mismatched quotes, or is this just a single case?

**Comment by akshay196** [comment]
@bfahr Following mismatched quotations occurred in a single case, (here  `'` and `’` are different.)

```
ADD_REGISTRY='--add-registry registry.access.redhat.com’
```
This was throwing exception as above. But this is not a common scenario.

After checking, I understand that mismatch quotes are not valid configuration. Services like docker fails to start if its configuration file contains mismatch quotations.

I am closing issue. Sorry to bother.
