### ISSUE TITLE
Invoking "insights-inspect" command without colorama installed results in a traceback

### ISSUE THREAD

**Issue by Rezney** [RedHatInsights/insights-core#1956]
```python
[root@localhost ~]# insights-inspect insights.parsers.yum_list_installed.YumListInstalled
Traceback (most recent call last):
  File "/usr/local/bin/insights-inspect", line 11, in <module>
    load_entry_point('insights-core', 'console_scripts', 'insights-inspect')()
  File "/root/insights-core/insights/tools/insights_inspect.py", line 231, in main
    run(component, archive=args.archive)
  File "/root/insights-core/insights/tools/insights_inspect.py", line 206, in run
    print(C.Fore.BLUE + "\nIPython Console Usage Info:\n" + C.Style.RESET_ALL, file=sys.stderr)
AttributeError: 'Pass' object has no attribute 'BLUE'
[root@localhost ~]#
```

**Comment by xiangce** [comment]
I can reproduce this issue and the #1957 fixed it.
