### ISSUE TITLE
uploader_map missing

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [RedHatInsights/insights-core#2733]
i observe `No such file or directory: '/home/rpfannsc/Projects/insights-qe/venv-iqe/lib/python3.8/site-packages/insights/uploader_json_map.json'` for `insights-core>3.0.170`

i suspect https://github.com/RedHatInsights/insights-core/blob/master/setup.py#L120 needs to be extended, but i cant verify soon myself

**Comment by bfahr** [comment]
@gravitypriest have you seen this?

**Comment by gravitypriest** [comment]
Oh lord

**Comment by gravitypriest** [comment]
Interesting... should be included in the package. Let me take a look in the morning.

**Comment by gravitypriest** [comment]
@RonnyPfannschmidt when do you receive this error? Build time, exec time? etc

**Comment by RonnyPfannschmidt** [comment]
Exec time

**Comment by gravitypriest** [comment]
Could you give me a quick set of steps to reproduce?

**Comment by RonnyPfannschmidt** [comment]
Will do when I get back to the computer

**Comment by RonnyPfannschmidt** [comment]
```
[rpfannsc@ronny-t490-local insights-qe]$ virtualenv iqe-core-issue
created virtual environment CPython3.8.5.final.0-64 in 198ms
  creator CPython3Posix(dest=/home/rpfannsc/Projects/insights-qe/iqe-core-issue, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/rpfannsc/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[rpfannsc@ronny-t490-local insights-qe]$ . iqe-core-issue/bin/activate
(iqe-core-issue) [rpfannsc@ronny-t490-local insights-qe]$ pip install insights-core
Collecting insights-core
  Downloading insights-core-3.0.193.tar.gz (1.4 MB)
     |████████████████████████████████| 1.4 MB 1.3 MB/s 
Collecting cachecontrol[redis]
  Using cached CacheControl-0.12.6-py2.py3-none-any.whl (19 kB)
Processing /home/rpfannsc/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c/PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl
Collecting lockfile
  Using cached lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Collecting requests
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting defusedxml
  Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting jinja2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting redis
  Using cached redis-3.5.3-py2.py3-none-any.whl (72 kB)
Collecting msgpack>=0.5.2
  Using cached msgpack-1.0.0-cp38-cp38-manylinux1_x86_64.whl (303 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 8.9 MB/s 
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Building wheels for collected packages: insights-core
  Building wheel for insights-core (setup.py) ... done
  Created wheel for insights-core: filename=insights_core-3.0.193-py3-none-any.whl size=1824466 sha256=d8b90a615845d7c4d31e65956e206f1668fb384ff0f25055022cd966919aeec3
  Stored in directory: /home/rpfannsc/.cache/pip/wheels/15/57/b1/ed5d9257b6bb47fc9f591648d0f2c0db336d5decad3efedbbe
Successfully built insights-core
Installing collected packages: msgpack, urllib3, certifi, idna, chardet, requests, redis, cachecontrol, pyyaml, lockfile, six, defusedxml, MarkupSafe, jinja2, insights-core
Successfully installed MarkupSafe-1.1.1 cachecontrol-0.12.6 certifi-2020.6.20 chardet-3.0.4 defusedxml-0.6.0 idna-2.10 insights-core-3.0.193 jinja2-2.11.2 lockfile-0.12.2 msgpack-1.0.0 pyyaml-5.3.1 redis-3.5.3 requests-2.24.0 six-1.15.0 urllib3-1.25.11
WARNING: You are using pip version 20.1; however, version 20.2.4 is available.
You should consider upgrading via the '/home/rpfannsc/Projects/insights-qe/iqe-core-issue/bin/python -m pip install --upgrade pip' command.
(iqe-core-issue) [rpfannsc@ronny-t490-local insights-qe]$ python -c 'import insights'
(iqe-core-issue) [rpfannsc@ronny-t490-local insights-qe]$ python -c 'from insights.client.constants import InsightsConstants'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rpfannsc/Projects/insights-qe/iqe-core-issue/lib/python3.8/site-packages/insights/client/__init__.py", line 13, in <module>
    from . import client
  File "/home/rpfannsc/Projects/insights-qe/iqe-core-issue/lib/python3.8/site-packages/insights/client/client.py", line 11, in <module>
    from .utilities import (generate_machine_id,
  File "/home/rpfannsc/Projects/insights-qe/iqe-core-issue/lib/python3.8/site-packages/insights/client/utilities.py", line 26, in <module>
    from .collection_rules import InsightsUploadConf, load_yaml
  File "/home/rpfannsc/Projects/insights-qe/iqe-core-issue/lib/python3.8/site-packages/insights/client/collection_rules.py", line 19, in <module>
    from .map_components import map_rm_conf_to_components
  File "/home/rpfannsc/Projects/insights-qe/iqe-core-issue/lib/python3.8/site-packages/insights/client/map_components.py", line 14, in <module>
    uploader_json_file = pkgutil.get_data(insights.__name__, "client/uploader_json_map.json")
  File "/usr/lib64/python3.8/pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/rpfannsc/Projects/insights-qe/iqe-core-issue/lib/python3.8/site-packages/insights/client/uploader_json_map.json'
(iqe-core-issue) [rpfannsc@ronny-t490-local insights-qe]$ 
```

so its as quick as 

```
$ virtualenv example && example/bin/pip install insights-core && example/bin/python -c "from insights.client.constants import InsightsConstants"
```

**Comment by RonnyPfannschmidt** [comment]
i believe modern python tooling making a wheel and installing that leaves the file out as its not part of the declared package data

**Comment by gravitypriest** [comment]
Thanks very much! I'll reproduce and patch this asap
