### ISSUE TITLE
YumRepolist parser throws an exception parsing valid repolist data

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2857]
The [YumRepolist parser](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/yum.py) throws an exception when attempting to parse valid output:

```
$ insights inspect insights.combiners.cloud_provider.CloudProvider archive
Traceback (most recent call last):
  File "/home/bfahr/work/insights/insights-core/insights/core/dr.py", line 962, in run
    result = DELEGATES[component].process(broker)
  File "/home/bfahr/work/insights/insights-core/insights/core/dr.py", line 681, in process
    return self.invoke(broker)
  File "/home/bfahr/work/insights/insights-core/insights/core/plugins.py", line 130, in invoke
    return self.component(dep_value)
  File "/home/bfahr/work/insights/insights-core/insights/core/__init__.py", line 598, in __init__
    super(CommandParser, self).__init__(context)
  File "/home/bfahr/work/insights/insights-core/insights/core/__init__.py", line 92, in __init__
    self._handle_content(context)
  File "/home/bfahr/work/insights/insights-core/insights/core/__init__.py", line 95, in _handle_content
    self.parse_content(context.content)
  File "/home/bfahr/work/insights/insights-core/insights/parsers/yum.py", line 145, in parse_content
    empty_exception=True)
  File "/home/bfahr/work/insights/insights-core/insights/parsers/__init__.py", line 342, in parse_fixed_table
    first_line = calc_offset(table_lines, heading_ignore)
  File "/home/bfahr/work/insights/insights-core/insights/parsers/__init__.py", line 276, in calc_offset
    raise ValueError("Line containing '{}' was not found in table".format(','.join(target)))
ValueError: Line containing 'repo id' was not found in table
```

Caused by output of `yum -C --noplugins repolist` having the output:

```
repolist: 0
```

**Comment by bfahr** [comment]
This exception was raised in Bugzilla 1939384.
