### ISSUE TITLE
ValueError: could not convert string to float: '11:29' 

### ISSUE THREAD

**Issue by rameshsahoo111** [RedHatInsights/insights-core#2886]
$ insights-inspect insights.combiners.ps.Ps ~/scripts/rhel7_sosreport/
Traceback (most recent call last):
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 962, in run
    result = DELEGATES[component].process(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 681, in process
    return self.invoke(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/plugins.py", line 64, in invoke
    return super(PluginType, self).invoke(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 661, in invoke
    return self.component(*args)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 125, in __init__
    self.__convert_data_types()
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 260, in __convert_data_types
    for attr_name in self.__CONVERSION_MAP
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 262, in <listcomp>
    if attr_name in row]
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 257, in convert_attr
    row[attr_name] = type_ctor(row[attr_name])
ValueError: could not convert string to float: '11:29'

Traceback (most recent call last):
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 962, in run
    result = DELEGATES[component].process(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 681, in process
    return self.invoke(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/plugins.py", line 64, in invoke
    return super(PluginType, self).invoke(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 661, in invoke
    return self.component(*args)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 125, in __init__
    self.__convert_data_types()
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 260, in __convert_data_types
    for attr_name in self.__CONVERSION_MAP
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 262, in <listcomp>
    if attr_name in row]
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 257, in convert_attr
    row[attr_name] = type_ctor(row[attr_name])
ValueError: could not convert string to float: '11:29'

**Comment by xiangce** [comment]
@rameshsahoo111 - Thanks for opening this issue, please provide a sample slice of the impacted "ps" output, which is helpful to debug and troubleshoot. Thanks.

**Comment by rameshsahoo111** [comment]
@xiangce please check my ping in the Red Hat Gchat for the sample test case.

**Comment by xiangce** [comment]
@rameshsahoo111 - I get the following lines from the sosreport that you shared with me:

```
# head -1 rhel7_sosreport/sos_commands/process/ps_auxwww; tail -5 rhel7_sosreport/sos_commands/process/ps_auxwww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     18031  0.0  0.0      0     0 ?        S    22:04   0:00 [kworker/0:1]
root     22046  0.0  0.0      0     0 ?        S    22:13   0:00 [kworker/3:1]
root     23015  0.0  0.0      0     0 ?        S    22:16   0:00 [kworker/1:1]
ntp 15026 1 0 11:29 ? 00:00:00 ntpd -u ntp:ntp -p /var/run/ntpd.pid -g -p /var/run/ntpd.pid -g
root 15029 15026 0 11:29 ? 00:00:00 ntpd -u ntp:ntp -p /var/run/ntpd.pid -g -p /var/run/ntpd.pid -g
```
in which the fourth column should be the `VSZ` which is the short of `"virtual memory size of the process in KiB (1024-byte units)."` and should be in `int` or `float` type. But in the sosreport you used, it's `11:29` which is invalid.

And I believe the last two lines are invalid for the `ps auxwww` command, for these invalid lines, it's expected that the above `ValueError` is thrown.

Please double confirm if the sosreport a valid one. Thanks.

**Comment by bfahr** [comment]
I spoke with @rameshsahoo111 and this issue can be closed as the parser is correctly throwing an error in this case.
