### ISSUE TITLE
Unexpected Exception is thrown while running insights-client

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#2920]
```
# insights-client 
Starting to collect Insights data for slutade-rhel7.syslab.pnq2.redhat.com
Traceback (most recent call last):
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 962, in run
    result = DELEGATES[component].process(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 681, in process
    return self.invoke(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/plugins.py", line 90, in invoke
    return self.component(broker)
  File "/var/lib/insights/last_stable.egg/insights/specs/default.py", line 282, in cloud_cfg
    with open(relative_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/etc/cloud/cloud.cfg'

```

The current `cloud_cfg` datasource caught the OSError instead of IOError.
https://github.com/RedHatInsights/insights-core/blob/1b2d8055dae1f6608901a1cc30f8ac978af71063/insights/specs/default.py#L288

**Comment by xiangce** [comment]
More:

Nothing more to see, output says it all. Backtraces should never happen.
Looks like multiple bugs here:
- some insights-diplay-name handling bug
- lssap parsing
- reading of /etc/cloud/cloud.cfg without checking if it exists

-------------
vrempet-admin@hiltiq.com@li-lc-1726 ~
$ sudo insights-client --version
Client: 3.1.1
Core: 3.0.207-1

vrempet-admin@hiltiq.com@li-lc-1726 ~
$ sudo insights-client
Fatal error
Traceback (most recent call last):
  File "/var/lib/insights/last_stable.egg/insights/client/phase/v1.py", line 32, in _f
    func(client, config)
  File "/var/lib/insights/last_stable.egg/insights/client/phase/v1.py", line 182, in post_update
    if client.set_display_name(config.display_name):
  File "/var/lib/insights/last_stable.egg/insights/client/__init__.py", line 73, in _init_connection
    return func(self, *args, **kwargs)
  File "/var/lib/insights/last_stable.egg/insights/client/__init__.py", line 507, in set_display_name
    return self.connection.set_display_name(display_name)
  File "/var/lib/insights/last_stable.egg/insights/client/connection.py", line 966, in set_display_name
    return self._legacy_set_display_name(display_name)
  File "/var/lib/insights/last_stable.egg/insights/client/connection.py", line 932, in _legacy_set_display_name
    old_display_name = json.loads(res.content).get('display_name', None)
AttributeError: 'unicode' object has no attribute 'get'
Starting to collect Insights data for [crash/LI/SAP-App/B03-SAP-di] li-lc-1726.hag.hilti.com
Traceback (most recent call last):
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 962, in run
    result = DELEGATES[component].process(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 681, in process
    return self.invoke(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/plugins.py", line 130, in invoke
    return self.component(dep_value)
  File "/var/lib/insights/last_stable.egg/insights/core/__init__.py", line 598, in __init__
    super(CommandParser, self).__init__(context)
  File "/var/lib/insights/last_stable.egg/insights/core/__init__.py", line 92, in __init__
    self._handle_content(context)
  File "/var/lib/insights/last_stable.egg/insights/core/__init__.py", line 95, in _handle_content
    self.parse_content(context.content)
  File "/var/lib/insights/last_stable.egg/insights/parsers/lssap.py", line 61, in parse_content
    raise ParseException("Lssap: Unable to parse {0} line(s) of content: ({1})".format(len(content), content))
ParseException: Lssap: Unable to parse 10 line(s) of content: ([u'*** ERROR => CTrcOpen: fopen dev_lssap', u'', u'---------------------------------------------------', u'trc file: "dev_lssap", trc level: 1, release: "721"', u'---------------------------------------------------', u' - lssap version 1.0 -', u'==========================================', u'  SID   Nr   Instance    SAPLOCALHOST                        Version                 DIR_EXECUTABLE', u'  D02|  50|       D50|     sapcbapp08|722, patch 201, changelist 1718183|          /usr/sap/D02/D50/exe', u'=========================================='])

Traceback (most recent call last):
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 962, in run
    result = DELEGATES[component].process(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 681, in process
    return self.invoke(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/plugins.py", line 90, in invoke
    return self.component(broker)
  File "/var/lib/insights/last_stable.egg/insights/specs/default.py", line 282, in cloud_cfg
    with open(relative_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/etc/cloud/cloud.cfg'

Uploading Insights data.
Successfully uploaded report from [crash/LI/SAP-App/B03-SAP-di] li-lc-1726.hag.hilti.com to account 694947.
View details about this system on cloud.redhat.com:
https://cloud.redhat.com/insights/inventory/49b856b3-bb93-44eb-b05c-f697014e8257

vrempet-admin@hiltiq.com@li-lc-1726 ~
$
-----------

**Comment by bfahr** [comment]
PR #2921 was merged fixing this issue.
