### ISSUE TITLE
Exception occurs in ConfigCombiner when the main conf doesn't exist.

### ISSUE THREAD

**Issue by ryan-blakley** [RedHatInsights/insights-core#3276]
This was reproduced by installing nginx then moving /etc/nginx/nginx.conf to /etc/nginx/nginx.conf.bak, but it could occur with any combiner using ConfigCombiner and the main_file argument doesn't exist in confs.

Traceback (most recent call last):
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 967, in run
    result = DELEGATES[component].process(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 686, in process
    return self.invoke(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/plugins.py", line 64, in invoke
    return super(PluginType, self).invoke(broker)
  File "/var/lib/insights/last_stable.egg/insights/core/dr.py", line 666, in invoke
    return self.component(*args)
  File "/var/lib/insights/last_stable.egg/insights/combiners/nginx_conf.py", line 73, in __init__
    super(NginxConfTree, self).__init__(confs, "nginx.conf", eq("include"))
  File "/var/lib/insights/last_stable.egg/insights/core/__init__.py", line 374, in __init__
    server_root = self.conf_path
  File "/var/lib/insights/last_stable.egg/insights/combiners/nginx_conf.py", line 77, in conf_path
    return os.path.dirname(self.main.file_path)
AttributeError: 'NoneType' object has no attribute 'file_path'

**Comment by bfahr** [comment]
[Bugzilla 2019837](https://bugzilla.redhat.com/show_bug.cgi?id=2019837)
