### ISSUE TITLE
Sap Combiner cannot work with old archives.

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#3530]
After the #3512, when run the insights against a old archive, the following error is reported:

```
Traceback (most recent call last):
  File "/Users/liuxc/work/insights/insights-core/insights/core/dr.py", line 967, in run
    result = DELEGATES[component].process(broker)
  File "/Users/liuxc/work/insights/insights-core/insights/core/dr.py", line 686, in process
    return self.invoke(broker)
  File "/Users/liuxc/work/insights/insights-core/insights/core/plugins.py", line 64, in invoke
    return super(PluginType, self).invoke(broker)
  File "/Users/liuxc/work/insights/insights-core/insights/core/dr.py", line 666, in invoke
    return self.component(*args)
  File "/Users/liuxc/work/insights/insights-core/insights/combiners/sap.py", line 103, in __init__
    inst['InstanceType'],
KeyError: 'InstanceType'
```

**Comment by xiangce** [comment]
This will be resolved by #3528
