### ISSUE TITLE
Unexpected Traceback messages of "luksmeta" spec?

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#3584]
The new `luksmeta` reports the following errors on some of the hosts, can we skip these non-luks devices when running the `luksmeta` command or handle the following `Traceback` messages in a more grace way?

```
2022-11-04 15:10:28,825    DEBUG insights.core.spec_factory Traceback (most recent call last):
  File "/var/lib/insights/newest.egg/insights/core/spec_factory.py", line 902, in __call__
    timeout=self.timeout, inherit_env=self.inherit_env, signum=self.signum)
  File "/var/lib/insights/newest.egg/insights/core/spec_factory.py", line 323, in __init__
    self.validate()
  File "/var/lib/insights/newest.egg/insights/core/spec_factory.py", line 335, in validate
    raise ContentException("Couldn't execute: %s" % self.cmd)
ContentException: Couldn't execute: /usr/bin/luksmeta show -d /dev/disk/by-uuid/00ac3486-3f3f-4bf8-a360-751aa1d7d13d

2022-11-04 15:10:28,825    DEBUG insights.core.spec_factory Traceback (most recent call last):
  File "/var/lib/insights/newest.egg/insights/core/spec_factory.py", line 902, in __call__
    timeout=self.timeout, inherit_env=self.inherit_env, signum=self.signum)
  File "/var/lib/insights/newest.egg/insights/core/spec_factory.py", line 323, in __init__
    self.validate()
  File "/var/lib/insights/newest.egg/insights/core/spec_factory.py", line 335, in validate
    raise ContentException("Couldn't execute: %s" % self.cmd)
ContentException: Couldn't execute: /usr/bin/luksmeta show -d /dev/disk/by-uuid/72bcfb1e-5f08-477f-a066-f47efd5ba6a3

```

**Comment by bfahr** [comment]
@xiangce this exception is raised from a `foreach_execute` that depends on the `block_devices_by_uuid` datasource for inputs.  If the command does not exist on a system should the datasource ever execute?  Should have raised a `SkipException` before it ever got to the `foreach_execute`?

**Comment by xiangce** [comment]
@bfahr - Makes sense to me, it is a good idea to prevent the spec from entering the `foreach_execute` if the command doesn't exist at all. Sorry for checking your comment late (after merging the #3628), but it looks more like a new issue, I'll open a new issue regarding this point. Thanks.
