### ISSUE TITLE
Unhandled Exception in 'gluster_peer_status' parser

### ISSUE THREAD

**Issue by lhuett** [RedHatInsights/insights-core#3720]
In some cases the gluster daemon may not be running on the server, in this case the "content" arg in the parser may contain ['Connection failed. Please check if gluster daemon is operational.'], which will cause the following exception in the [parser](https://github.com/RedHatInsights/insights-core/blob/984bc1a2875dc4e797188a5fab3871fc052b6df0/insights/parsers/gluster_peer_status.py#L58) :

"Traceback (most recent call last):
  File "<some_path>/insights/core/dr.py", line 1040, in run_components
    result = DELEGATES[component].process(broker)
  File "<some_path>/insights/core/dr.py", line 767, in process
    return self.invoke(broker)
  File "<some_path>/insights/core/plugins.py", line 151, in invoke
    return self.component(dep_value)
  File "<some_path>/insights/core/__init__.py", line 632, in __init__
    super(CommandParser, self).__init__(context)
  File "<some_path>/insights/core/__init__.py", line 90, in __init__
    self._handle_content(context)
  File "<some_path>/insights/core/__init__.py", line 93, in _handle_content
    self.parse_content(context.content)
  File "<some_path>/insights/parsers/gluster_peer_status.py", line 58, in parse_content
    self.status['peers'] = int(content[0].split(':')[-1].strip())
ValueError: invalid literal for int() with base 10: 'Connection failed. Please check if gluster daemon is operational.'"

The parser already evaluates the content, may also need to check the content for something like "Connection failed"

**Comment by xiangce** [comment]
resolved by #3768
