### ISSUE TITLE
Cannot load "version_info" when the collecting egg version is old like 3.0.246

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#3936]
For the archives that are collected with old EGGs, e.g. `3.0.246`, the insights cannot load the built-in files e.g. version_info correctly:

```
❯ cat /tmp/insights/insights-gcsbd6hydrsb550.cedelgroup.com-20231014224508/version_info
{"core_version": "3.0.246-1", "client_version": "3.1.7"}

❯ insights-cat insights.specs.Specs.version_info /tmp/insights/insights-gcsbd6hydrsb550.cedelgroup.com-20231014224508
...
Traceback (most recent call last):
  File "/Users/liuxc/work/insights/insights-core/insights/core/plugins.py", line 98, in invoke
    return self.component(broker)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 624, in __call__
    return self.kind(ctx.locate_path(self.path), root=ctx.root, ds=self, ctx=ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 180, in __init__
    super(MetadataProvider, self).__init__(relative_path, root, ds, ctx)
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 138, in __init__
    self.validate()
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 200, in validate
    super(MetadataProvider, self).validate()
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 154, in validate
    raise ContentException("%s does not exist." % self.path)
insights.core.exceptions.ContentException: /tmp/insights/insights-gcsbd6hydrsb550.cedelgroup.com-20231014224508/data/version_info does not exist.

Traceback (most recent call last):
  File "/Users/liuxc/work/insights/insights-core/insights/core/plugins.py", line 98, in invoke
    return self.component(broker)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 624, in __call__
    return self.kind(ctx.locate_path(self.path), root=ctx.root, ds=self, ctx=ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 138, in __init__
    self.validate()
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 154, in validate
    raise ContentException("%s does not exist." % self.path)
insights.core.exceptions.ContentException: /tmp/insights/insights-gcsbd6hydrsb550.cedelgroup.com-20231014224508/data/version_info does not exist.

Missing Dependencies:
    At Least One Of:
        insights.specs.default.DefaultSpecs.version_info
        insights.specs.insights_archive.InsightsArchiveSpecs.version_info
        insights.specs.core3_archive.Core3Specs.version_info
```

**Comment by xiangce** [comment]
Resolved by https://github.com/RedHatInsights/insights-core/pull/3937
