### ISSUE TITLE
Parser error in `ntp_sources.py`

### ISSUE THREAD

**Issue by miclark** [RedHatInsights/insights-core#677]
Testing against production archives, the following exception occurred 24 times:
```
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 635, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 594, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/ntp_sources.py", line 82, in parse_content
    k, v = line.split("=")
ValueError: too many values to unpack
```

**Comment by xiangce** [comment]
Another error found in `ntp_sources.py` when test with some `insights-cli`:

~~~
Reducer telemetry.rules.plugins.kernel.ntpd_not_reset_leap_status.report failed                
Traceback (most recent call last):                                                                                                                                                             
  File "/home/liuxc/work/insights/local_insights_CLI/insights-core/insights/core/reducer.py", line 158, in run_reducer                                                                         
    r = plugins.DELEGATES[func](local, shared)                                                                                                                                                 
  File "/home/liuxc/work/insights/local_insights_CLI/insights-core/insights/core/plugins.py", line 483, in __f                                                                                 
    return executor(func, local, broker, shared=is_shared, cluster=cluster, emitter=emitter)   
  File "/home/liuxc/work/insights/local_insights_CLI/insights-core/insights/core/plugins.py", line 431, in default_executor                                                                    
    return func(local, broker)                                                                 
  File "/home/liuxc/work/insights/local_insights_CLI/insights-plugins/telemetry/rules/plugins/kernel/ntpd_not_reset_leap_status.py", line 46, in report                                        
    leap_val = shared[NtpqLeap].leap                                                                                                                                                           
  File "/home/liuxc/work/insights/local_insights_CLI/insights-core/insights/parsers/ntp_sources.py", line 84, in leap                                                                          
    if self.data:                              
AttributeError: 'NtpqLeap' object has no attribute 'data'    
~~~

**Comment by xiangce** [comment]
Open another issue #727 for above error.
