### ISSUE TITLE
Parser error in iptables.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#779]
```
Instances: 2965
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/iptables.py", line 146, in parse_content
    constraints, target = [i.strip() for i in rule.split(target_option[-1])]
ValueError: too many values to unpack
```
```
Instances: 405
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/iptables.py", line 143, in parse_content
    chain_name, rule = line[3:].split(None, 1)
ValueError: need more than 1 value to unpack
```

**Comment by miclark** [comment]
Closing as a stale bug to be reconsidered if reported after 3.x migration.
