### ISSUE TITLE
Parser error in LsPci in lspci.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#780]
```
Instances: 716
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 63, in rule_executor
    r = compat_executor(component, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 56, in compat_executor
    return component({}, broker)
  File "build/bdist.linux-x86_64/egg/telemetry/rules/plugins/kernel/intel5500_interrupt_remapping_failure.py", line 61, in report
    chip_info = _check_lspci(shared[LsPci].get(INTEL_STR))
  File "build/bdist.linux-x86_64/egg/telemetry/rules/plugins/kernel/intel5500_interrupt_remapping_failure.py", line 29, in _check_lspci
    l = INTEL_LIST.match(line)
TypeError: expected string or buffer
```
```
 27 def _check_lspci(in_list):
 28     for line in in_list:
 29         l = INTEL_LIST.match(line)
 30         if l:
 31             return l.group(0)
 32     return None
 ...
 61     chip_info = _check_lspci(shared[LsPci].get(INTEL_STR))
```

**Comment by xiangce** [comment]
`get` returns a list of dicts instead of a list of strings in the 3.x

**Comment by miclark** [comment]
Closing as a stale bug to be reconsidered if reported after 3.x migration.
