### ISSUE TITLE
Parser error in dockerinfo.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#782]
```
Instances: 350
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 63, in rule_executor
    r = compat_executor(component, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 56, in compat_executor
    return component({}, broker)
  File "build/bdist.linux-x86_64/egg/telemetry/rules/plugins/container/docker_host_metadata.py", line 53, in report
    container_count = docker_info.data["Containers"]
KeyError: 'Containers'
```

**Comment by miclark** [comment]
Closing as a stale bug to be reconsidered if reported after 3.x migration.

**Comment by wushiqinlou** [comment]
When we use parser `dockerinfo`,  function `get` is necessary, like `docker_info.data.get("Containers")`. I have already enhanced the plugins using this parser incorrectly in track3.0.

https://github.com/RedHatInsights/insights-plugins/pull/684
