### ISSUE TITLE
Parser error in lvm.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#784]
```
Instances: 192
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/lvm.py", line 103, in parse_content
    d["content"] = list(map_keys(parse_keypair_lines(content), self.KEYS))
  File "build/bdist.linux-x86_64/egg/insights/util/__init__.py", line 112, in parse_keypair_lines
    key, value = [i.strip("'\"").strip() for i in item.strip().split(kv_sep)]
ValueError: need more than 1 value to unpack
```
```
Instances: 120
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/lvm.py", line 103, in parse_content
    d["content"] = list(map_keys(parse_keypair_lines(content), self.KEYS))
  File "build/bdist.linux-x86_64/egg/insights/util/__init__.py", line 112, in parse_keypair_lines
    key, value = [i.strip("'\"").strip() for i in item.strip().split(kv_sep)]
ValueError: too many values to unpack
```

**Comment by miclark** [comment]
Closing as a stale bug to be reconsidered if reported after 3.x migration.
