### ISSUE TITLE
Parser error in rabbitmq.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#786]
```
Instances: 166
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/rabbitmq.py", line 195, in parse_content
    raise ParseException("Data appears invalid: {0}".format(line))
ParseException: Data appears invalid: ...done.
```

**Comment by koalakangaroo** [comment]
same with https://github.com/RedHatInsights/insights-core/issues/680
