### ISSUE TITLE
Parser error in lssap.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#787]
```
Instances: 147
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/parsers/lssap.py", line 59, in __init__
    super(Lssap, self).__init__(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/lssap.py", line 74, in parse_content
    raise ParseException("Lssap: Invalid instance parsed in content: {0}".format(invalid_inst))
ParseException: Lssap: Invalid instance parsed in content: ['SMDA']
```

**Comment by miclark** [comment]
Closing as a stale bug to be reconsidered if reported after 3.x migration.
