### ISSUE TITLE
Parser error in fstab.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#788]
```
Instances: 114
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/fstab.py", line 123, in parse_content
    line['fs_mntops'] = AttributeDict(optlist_to_dict(line['raw_fs_mntops']))
KeyError: 'raw_fs_mntops'
```
```
Instances: 112
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/fstab.py", line 125, in parse_content
    line['raw'] = [l for l in content if l.startswith(line['fs_spec'])][0]
IndexError: list index out of range
```

**Comment by miclark** [comment]
Closing as a stale bug to be reconsidered if reported after 3.x migration.
