### ISSUE TITLE
Parser error in scsi.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#789]
```
Instances: 80
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/scsi.py", line 63, in parse_content
    raise ParseException("Empty content of file /proc/scsi/scsi", content)
ParseException: ('Empty content of file /proc/scsi/scsi', [])
```

**Comment by miclark** [comment]
Closing as a stale bug to be reconsidered if reported after 3.x migration.
