### ISSUE TITLE
Parser error in lsblk.py

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#790]
```
Instances: 66
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 639, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 598, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/lsblk.py", line 306, in parse_content
    "TYPE not found in LsBlockPairs line '{l}'".format(l=line)
ParseException: TYPE not found in LsBlockPairs line '/bin/lsblk: invalid option -- 'P''
```

**Comment by miclark** [comment]
Closing as a stale bug to be reconsidered if reported after 3.x migration.
