### ISSUE TITLE
Modify behavior of --support

### ISSUE THREAD

**Issue by gravitypriest** [RedHatInsights/insights-core#904]
Use `--support` to collect the multiple logs (client log + systemd logs) into one tarfile for upload

**Comment by YakovLittle** [comment]
>insights-client --vers
Client: 3.0.3-9
Core: 3.0.35-1

>insights-client --support
Fatal error
Traceback (most recent call last):
  File "/var/lib/insights/last_stable.egg/insights/client/phase/v1.py", line 34, in _f
    func(client, config)
  File "/var/lib/insights/last_stable.egg/insights/client/phase/v1.py", line 103, in pre_update
    support = InsightsSupport()
TypeError: __init__() takes exactly 2 arguments (1 given)

**Comment by Glutexo** [comment]
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1607803

**Comment by Glutexo** [comment]
@gravitypriest Is this issue still relevant? If so, would you please tell me, what logs exactly are going to be uploaded? Like, the full output of the `journalctl` command or the commands mentioned in the related [Bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1607803)?

```
systemctl cat insights-client.timer
systemctl cat insights-client.service
systemctl status insights-client.timer
systemctl status insights-client.service
```

Could you please take a look at the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1607803) and tell me whether it describes the same problem as this GitHub issue? To me it looks like that this issue describes a RFE that the _systemd_ logs should be added, but the BZ on the other hand looks like it is already there, but not working. Thanks!
