### ISSUE TITLE
Client halts if egg download fails

### ISSUE THREAD

**Issue by kylape** [RedHatInsights/insights-core#925]
The correct behavior would be to continue execution without updating the egg, optionally trying again one or more times before moving on.

**Comment by kylape** [comment]
```
[root@vagrant-host vagrant]# iptables -A OUTPUT -p tcp --dport 443 -j REJECT
[root@vagrant-host vagrant]# insights-client --net-debug
GET https://cert-api.access.redhat.com/r/insights/v1/branch_info
Could not auto configure, falling back to static config
GET https://cert-api.access.redhat.com/r/insights/v1/branch_info
Could not auto configure, falling back to static config
GET https://cert-api.access.redhat.com/r/insights/v1/static/core/insights-core.egg
Fatal error
Traceback (most recent call last):
  File "/etc/insights-client/rpm.egg/insights/client/phase/v1.py", line 29, in _f
    func()
  File "/etc/insights-client/rpm.egg/insights/client/phase/v1.py", line 112, in update
    c.update()
  File "/etc/insights-client/rpm.egg/insights/client/__init__.py", line 171, in update
    egg_paths = self.fetch()
  File "/etc/insights-client/rpm.egg/insights/client/__init__.py", line 84, in fetch
    force)
  File "/etc/insights-client/rpm.egg/insights/client/__init__.py", line 126, in _fetch
    response = self.session.get(url)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
[root@vagrant-host vagrant]#
```
